const actions = {
  GET_COMPANIES_LOADING: "GET_COMPANIES_LOADING",
  GET_COMPANIES_SUCCEED: "GET_COMPANIES_SUCCESS",
  GET_COMPANIES_FAILED: "GET_COMPANIES_FAILED",
  ADD_COMPANIES_LOADING: "ADD_COMPANIES_LOADING",
  ADD_COMPANIES_SUCCEED: "ADD_COMPANIES_SUCCESS",
  ADD_COMPANIES_FAILED: "ADD_COMPANIES_FAILED",
  CHANGE_MODAL_VISIBILITY: "CHANGE_MODAL_VISIBILITY",
  COMPANIES_SEARCH: "COMPANIES_SEARCH",
  FILTER_COMPANIES: "FILTER_COMPANIES",
  REST_FILTERS_AND_SEARCH: "REST_FILTERS_AND_SEARCH"
};

export default actions;
